### PR TITLE
Better init script

### PR DESCRIPTION
**Pull request by ytjohn**
- enable start/stop/restart and pid monitoring
 - put logs in /var/log/rackhd

https://github.com/RackHD/on-http/issues/416

### CODE REVIEW

**Comment by ytjohn** [comment]
Hold up on this - still has issues relating to background task. Might implement start-stop-daemon.

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by jimturnquist** [comment]
I loaded this on an appliance running RackHD and verified that start/stop/restart are working well.

+1

**Comment by ytjohn** [comment]
I did a bit more looking, and I realized I should add exit levels.  Let me push up a commit that includes those.

https://refspecs.linuxbase.org/LSB_3.0.0/LSB-PDA/LSB-PDA/iniscrptact.html

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
retest this please

**Comment by PengTian0** [comment]
test this please

**Comment by jimturnquist** [comment]
What is left for this to be merged?

**Comment by ytjohn** [comment]
All changes are pushed. Let me know if there's anything else preventing these from being merged in.

**Comment by ytjohn** [comment]
Added error message suggested by @davidzuhn 

```
root@rackhd01:~# /etc/init.d/on-taskgraph start
Service disabled due to absence of /etc/default/on-taskgraph
root@rackhd01:~# touch /etc/default/on-taskgraph
root@rackhd01:~# /etc/init.d/on-taskgraph start
on-taskgraph already running with pid 30132
```

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by jimturnquist** [comment]
Can we get this one merged? Is there anything left that is needed?

**Comment by benbp** [comment]
@jimturnquist just needs one more review :/ CC @RackHD/corecommitters (good to do this for every PR).

👍

**Comment by yyscamper** [comment]
:+1:

**Pull request merged**
